language: php
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="3.3.*"

matrix:
  include:
    - php: 7.1
      env: 
        - TEST_COVERAGE=true
    - php: 7.2

install:
  - phpenv config-rm xdebug.ini || echo "xDebug not disabled"
  - composer require symfony/symfony:${SYMFONY_VERSION:-"3.3.*"}

script: 
  - if [[ $TEST_COVERAGE ]]; then phpdbg -qrr vendor/bin/phpunit -c tests/ tests/ --coverage-clover ./build/logs/clover.xml; else vendor/bin/phpunit -c tests/ tests/; fi

after_success:
  - if [[ $TEST_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TEST_COVERAGE ]]; then php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
