language: php
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="3.3.*"

install:
  - phpenv config-rm xdebug.ini || echo "xDebug not disabled"
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: phpdbg -qrr vendor/bin/phpunit -c tests/ tests/ --coverage-clover ./build/logs/clover.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
