language: php

services:
  - mysql

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="3.3.*"

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION}

script:
  - cp tests/Functional/parameters.yml.dist tests/Functional/parameters.yml
  - rm -rf tests/Functional/cache
  - vendor/bin/phpunit -c tests/ tests/
