language: php
cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.*"
  - SYMFONY_VERSION="4.0.*"
  - PHPUNIT_VERSION="6.*"
  - PHPUNIT_VERSION="7.*"

matrix:
  include:
    - php: 7.1
      env: 
        - TEST_COVERAGE=true

install:
  - phpenv config-rm xdebug.ini || echo "xDebug not disabled"
  - composer require symfony/symfony:${SYMFONY_VERSION:-"3.3.*"} phpunit/phpunit:${PHPUNIT_VERSION:-"7.*"}

script: 
  - cp tests/Functional/parameters.yml.dist tests/Functional/parameters.yml
  - rm -rf tests/Functional/cache
  - if [[ $TEST_COVERAGE ]]; then phpdbg -qrr vendor/bin/phpunit -c tests/ --coverage-clover ./build/logs/clover.xml; else vendor/bin/phpunit -c tests/ tests/; fi
  - make phpstan

after_success:
  - if [[ $TEST_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TEST_COVERAGE ]]; then php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
